### ISSUE TITLE
[Request] List all DIDs in an Account Storage

### ISSUE THREAD

**Issue by cycraig** [iotaledger/identity.rs#567]
## Description
Add a method to list all DIDs stored in an `Account` `Storage` instance.

## Motivation
Prior to refactoring the `Account` to manage a single IOTA DID document, there was an `Account::list_identities` method to list all DIDs stored locally. A single Stronghold, for example, can contain multiple identities managed by separate `Accounts`, so it might still be useful to list which DIDs are stored in a local Stronghold file. The list should still be encrypted and require a password to access the snapshot so there should be no security risk in adding this.

## Requirements
Write a list of what you want this feature to do.

1. List the `IotaDIDs` of all DID documents in a `Storage` or `Stronghold` instance.

## Open questions (optional)

Still need to investigate if placing this method on the `Storage` interface or just the `Stronghold` struct is best, as requiring this for e.g. remote `Storage` implementations might not always make sense or even be possible.

We may also decide that this is unnecessary and that users should continue to manage lists of identities as they see fit rather than forcing a particular method.

## Are you planning to do it yourself in a pull request?

Probably not.

**Comment by PhilippGackstatter** [comment]
After thinking about it some more, I believe listing identities was removed because by itself, it is not all that useful. A DID is just a random identifier, so getting a list of them is not very helpful, unless I'm missing something? Instead we expect applications to ascribe meaning to each DID, such as having profiles that map to some DID.

So maybe we should enable users to store that mapping by exposing a generic key-value store via the `Storage` trait. That would make the trait more useful, in general, for all sorts of things users could store. We have to be careful with that, though, because that might give the impression that the storage can be treated like a database. But since our default storage is stronghold, and that is always completely in memory, it is not very suitable for storing large amounts of data. That should be made clear. For the mapping, it's more than fine.

**Comment by cycraig** [comment]
Well currently I believe there is no way of retrieving which DIDs are stored in a Stronghold file unless you have prior knowledge of them. This might be useful for backup restoration where one does not know which DIDs were stored in one's old Stronghold for instance, otherwise we expect users to devise their own backup strategies and store the DID index themselves too.

We expect applications to ascribe extra information to each DID but the question is whether that information needs to be secured/encrypted to the same degree as the private keys for instance. I think allowing the interface to treat a storage as a generic key-value database would lead to bloating the stronghold file significantly and thus degrade performance, which is not desirable.
